### ISSUE TITLE
More Polymorphic Functions

### ISSUE THREAD

**Issue by andrewthad** [andrewthad/linear-containers#8]
The `map` function from `Linear.List` is sadly less polymorphic than its counterpart in `Data.List`. While it is possible to write a more polymorphic `map`, it requires reallocating every cons cell.

**Comment by andrewthad** [comment]
Wait a minute. The `map` function in `Linear.List` *already* has to reallocate every cons cell.

**Comment by chessai** [comment]
yep

**Comment by andrewthad** [comment]
Nevermind. The real underlying problem ends up being `Linear.Reference.modify`. It has to be monomorphic. We could have a variant that can change the type of the payload, but it would free the original reference and allocate new memory.

That said, it is still possible to provide both flavors. The options are: (1) a rewrite rule when the types match or (2) another module for more polymorphic variants.

**Comment by andrewthad** [comment]
I lean toward the second option.

**Comment by chessai** [comment]
i like (2) better

**Comment by andrewthad** [comment]
As I think about it more, the utility of `map` on most of the data structures built here is minimal. The goal is to allow the user to have giant maps that live in unmanaged memory. Mapping over one of these would still be expensive because you would have to touch every value in the map. For the toy example of a singly-linked list, `map` seems less awful (since most algorithms operating on a linked list have to scan the whole thing anyway), but on many data structures with better performance characteristics, this operation isn't worth doing, monomorphically or polymorphically.

**Comment by andrewthad** [comment]
The unsound approach can still be found at https://github.com/andrewthad/linear-containers/tree/non_higher_kinded_static_reference. I'm closing this for now, but anyone can feel free to comment here if they have a breakthrough.
